name    'hmail-install'
version '0.1.0'
source  'https://github.com/PierrickI3/hmail-install'
author  'Pierrick Lozach'
license 'Apache License 2.0'
summary 'hMail server Module'
description 'hMail Installation Module for Puppet via Chocolatey'
project_page 'https://github.com/PierrickI3/hmail-install'

dependency 'rismoney/chocolatey', '>= 0.0.3'